---
AWSTemplateFormatVersion: "2010-09-09"
Description: "A demo cloud formation"
Parameters:
 Environment:
  Description: Environment Name
  Type: String

Resources:

 lambdaFunctionIamRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
     Version: '2012-10-17'
     Statement:
      - Effect: Allow
        Principal:
          Service: lambda.amazonaws.com
        Action: sts:AssumeRole
    Policies:
     - PolicyName: "demo-policy-for-lambda"
       PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'

 lambdaFunction:
  Type: AWS::Lambda::Function
  Properties:
    Description: This is a demo cloud formation program
    FunctionName: !Sub demo-cloudformation${Environment}
    Handler: CloudFormationSQS::CloudFormationSQS.Function::FunctionHandler
    MemorySize: 128
    Role: !GetAtt lambdaFunctionIamRole.Arn
    Runtime: dotnet6
    Timeout: 30
    Environment:
      Variables:
        key1: value1
    Code:
      S3Bucket: demo-cloudformation-package
      S3Key: lambda.zip
    Tags:
      - Key: keyname
        Value: value